### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by adRn-s** [flathub/org.jellyfin.JellyfinServer#108]
I can connect using 127.0.0.1 (from same PC that is running the app), but I'm unable to do so using the appropriate IP address remotely (i.e. from my laptop, within the same LAN, checked with another service, e.g. docker, and it works..)

According from what I read, the 'network' permission for flatpaks is all-or-none. I checked with flatseal (App to edit installed flatpaks permissions), and the network bit is 'ON'.

Can I have any suggestions on what could be wrong? I was very much looking forward to using flatpak instead of Docker for this, but in the upcoming days I might as well just go back to the container... I have no idea how to debug this. Any ideas will be very much appreciated. Sames goes if anyone can try reproducing the issue, and report back their results.

Thanks!

**Comment by cantalupo555** [comment]
Try this
https://github.com/flathub/org.jellyfin.JellyfinServer/issues/179#issuecomment-1860350301
