### ISSUE TITLE
Add a flag to disable opening browser after 10 seconds

### ISSUE THREAD

**Issue by Chillsmeit** [flathub/org.jellyfin.JellyfinServer#153]
At the moment I'm using the latest version of the jellyfin server flatpak and I use it to autorun at start.
The inconvenience is the browser opening up the webui after 10 seconds.
Is it possible to add a flag to disable this behaviour?

Thank you

**Comment by istori1** [comment]
It it possible to bypass this behavior by launching with the following command.

`flatpak run --command=jellyfin org.jellyfin.JellyfinServer`

**Comment by Chillsmeit** [comment]
Thank you! Is this information anywhere else? 
Or is it possible to write this info in the readme for example?
I've seen some people asking the same question as I did but in the main jellyfin repo
