### ISSUE TITLE
Flatpak package does not allow remote connections.

### ISSUE THREAD

**Issue by cantalupo555** [flathub/org.jellyfin.JellyfinServer#179]
I'm using Jellyfin's flatpak package:
https://flathub.org/apps/org.jellyfin.JellyfinServer

I notice that it is not allowing remote connection, even though it is enabled.
![image](https://github.com/flathub/org.jellyfin.JellyfinServer/assets/12485871/1d882894-0b49-4c0f-af36-6c3a46c2e5b0)

You can only access using "localhost".
![image](https://github.com/flathub/org.jellyfin.JellyfinServer/assets/12485871/8e6401b8-a2c4-422d-a1ea-2565acd27806)

**Comment by cantalupo555** [comment]
After restarting the machine a few times I realized that it is now possible to access remotely.
![image](https://github.com/flathub/org.jellyfin.JellyfinServer/assets/12485871/85b3e9cf-51f3-49d1-8ff3-27153e2045e5)

![image](https://github.com/flathub/org.jellyfin.JellyfinServer/assets/12485871/a868e214-7026-44c0-af7f-f8089c298db2)

![image](https://github.com/flathub/org.jellyfin.JellyfinServer/assets/12485871/c3f377bd-b242-4720-a238-26defe5d9d37)

**Comment by lwbt** [comment]
> After restarting a few times I realized that it is now possible to access remotely.
> 
> ```
> flatpak kill org.jellyfin.JellyfinServer
> flatpak run org.jellyfin.JellyfinServer
> ```

Sounds like you solved your problem. Instead of using `flatpak kill` I recommend going to the dashboard and either restart with just the restart button, or use the shutdown button and start the application either with `flatpak run` or through the desktop launcher icon.
