### ISSUE TITLE
Update jellyfin server to 10.9, 10.8 is no longer works with Android TV

### ISSUE THREAD

**Issue by gopikrishnansa** [flathub/org.jellyfin.JellyfinServer#295]
Update jellyfin server to 10.9, 10.8 is no longer works with Android TV, Iam getting a warning msg on my TV that says " need to update to version 10.9 or jellyfin wont work from next update

**Comment by parx01** [comment]
I posted the same in reddit Flatpak. It has been more than 7 months since they updated the Flatpak version. I find it easiest to setup and use. Flatpak version is not maintained by official team , rather by community. I hope those guys take out some time and update it for -less techie people like me.

**Comment by gopikrishnansa** [comment]
True, I mean, if they can't maintain it properly they can archive it

**Comment by oharaandrew314** [comment]
I don't know if the maintainer will keep this up to date any longer.

For those on debian based distributions, Jellyfin has an official repository that makes it easy to stay up to date.  Just make sure you stop and uninstall the flatpack before you install the new version.  You will, unfortunately, need to reconfigure your server

```bash
$ curl -s https://repo.jellyfin.org/install-debuntu.sh | sudo bash
```

**Comment by LinuxinaBit** [comment]
+1 for this

**Comment by lwbt** [comment]
I received permissions for this repository today and was able to push out the latest 10.09 build. 10.10 will be released soon.

```
$ curl -s https://flathub.org/apps/org.jellyfin.JellyfinServer | html2markdown | grep Changes
### Changes in version 10.9.11
```
