### ISSUE TITLE
Please update workflows and tooling to move to v10.9.z

### ISSUE THREAD

**Issue by lwbt** [flathub/org.jellyfin.JellyfinServer#359]
For PR https://github.com/flathub/org.jellyfin.JellyfinServer/pull/354 to succeed workflows / tooling / cache need to be updated

I will continue working on improvements, but this is a blocker now. The Jellyfin team plans to release the next version in [October](https://jellyfin.org/posts/jellyfin-release-10.9.0#the-next-version).

Until I can spend more time on the build system, to work around these issues, I will publish the builds I created locally for testing here:

<s>https://drive.google.com/drive/u/2/folders/1Ap2MMHWX2DMmJpKvbsQJOu67aK2DDGWR</s>

https://github.com/lwbt/org.jellyfin.JellyfinServer/releases

The PR for 10.10.z can be found here: https://github.com/flathub/org.jellyfin.JellyfinServer/pull/432

**Comment by vmazi** [comment]
Just wanted to say that the flatpak at the drive worked perfectly! thank you so much!! (FYI anyone using might need to get the firewall to let in incoming connections to the jellyfin port )

**Comment by lwbt** [comment]
Bumped to v10.9.10 https://github.com/flathub/org.jellyfin.JellyfinServer/pull/354/commits/b8ab8c2f445c5ea6959e1d414a040122ae9e688c

**Comment by lwbt** [comment]
> unable to connect soon unless server updates to 10.11

If you meant 10.9.11, then please have a look at: https://github.com/flathub/org.jellyfin.JellyfinServer/pull/354#issuecomment-2336781717

I added the update to the branch, which then built this test release to my surprise. I wanted to create a local build and upload it to google drive, but I got busy with many other tasks. :(

10.11 is another 6 months in the future, the next release is 10.10, which I will be looking into soon.
https://jellyfin.org/posts/release-roadmap-10.10.0

**Comment by vmazi** [comment]
the url at the pr gives a 404 when i curl it and flatpak install is giving same issue, are flathub/github creds needed for access to test build?

**Comment by lwbt** [comment]
**Bumped to v10.9.11 and uploaded to Google Drive.**

No you don't need any credentials. I was not sure if these builds get deleted or not. The documentation says builds get published after 3 hours automatically, but I have not found a statement yet about what happens to test builds.

**Comment by lwbt** [comment]
https://github.com/flathub/flathub/issues/3693#issuecomment-2442708600

Applied for maintainership.

v10.10 is in the works. I uploaded a version for AMD64 to Google Drive which uses FFmepg 6 instead of the newer FFmpeg 7, but you have been using this version with 10.9, so it should be fine while I'm figuring out how to build the newer version.

**Comment by lwbt** [comment]
**Bumped to v10.10.0 and uploaded to Google Drive.**

**Comment by vmazi** [comment]
> **Bumped to v10.10.0 and uploaded to Google Drive.**

Update Works flawlessly!!! Even the version with ffmpeg 7 works as needed.

NOTE - for anyone having problems, AV1 Encoding is only supported on Nvidia cards 4000 series and above. (That was my only issue that i had to deal with, disabling AV1 encoding fixed it)

**Comment by lwbt** [comment]
**Bumped to v10.10.1 and uploaded https://github.com/lwbt/org.jellyfin.JellyfinServer/releases**

I think that programmatic access through GitHub releases is the better approach while my PRs are not merged and Flathub is stuck on 10.8.z.

I plan to remove the Google Drive link and the files in about a month.

**Comment by lwbt** [comment]
**Bumped to v10.10.2.** https://github.com/lwbt/org.jellyfin.JellyfinServer/releases/tag/v10.10.2

In other news:

- https://github.com/flathub/org.jellyfin.JellyfinServer/pull/354 was merged, new builds should arrive soon
- https://github.com/flathub/flathub/issues/5849 I'm now a maintainer

**Comment by lwbt** [comment]
```
$ curl -s https://flathub.org/apps/org.jellyfin.JellyfinServer | html2markdown | grep Changes
### Changes in version 10.9.11
```

It's alive. :smile:

**Comment by lwbt** [comment]
```
$ curl -s https://flathub.org/apps/org.jellyfin.JellyfinServer | html2markdown | grep Changes
### Changes in version 10.10.2
```

Were are back on track.
