### ISSUE TITLE
Give jellyfin access to ~/.config/kcminputrc by default.

### ISSUE THREAD

**Issue by chikenpotpi** [flathub/org.jellyfin.JellyfinServer#400]
Without ~/.config/kcminputrc, it would default to breeze dark cursor theme atleast on KDE Plasma 6. Not sure if there's cursor theming issues on other desktop enviroments, if so, that should probably be looked into.

**Comment by lwbt** [comment]
I don't understand what the actual issue is you are having. The application starts as a web application in your default browser, it doesn't have a native desktop UI itself.

**Comment by lwbt** [comment]
I'm closing this issue as it does not appear to be reproducible to me and based on a misunderstanding.

If there is an actual issue with rendering the appropriate cursor theme for a desktop, then it is an issue with the application that responds to `xdg-open` on the respective desktop. Giving this Flatpak here read access to `~/.config/kcminputrc` by default will not change this behavior.
