### ISSUE TITLE
Being able to not automatically open the jellyfin link

### ISSUE THREAD

**Issue by lucasmz-dev** [flathub/org.jellyfin.JellyfinServer#500]
It is a bit annoying having Jellyfin always open the browser with the address it uses, I want it to start up with my system as a regular thing without messing with it as a service, and this is a bit annoying.

Having maybe an ENV variable to set this would be nice? Not sure if there's another way already

**Comment by lwbt** [comment]
https://github.com/flathub/org.jellyfin.JellyfinServer/wiki/FAQ-%E2%80%94-Frequently-Asked-Questions#how-to-launch-the-application

This question has been asked before in an issue and it is documented in the FAQ. You can bypass the launcher script and its behavior by starting the application binary directly.

**Comment by Puhpine4915** [comment]
from what i understand, you do not follow the behaviour of upstream. why not?
https://github.com/jellyfin/jellyfin/issues/2959#issuecomment-2930809780
